joint_state_broadcaster:
  type: joint_state_broadcaster/JointStateBroadcaster
  name: joint_state_broadcaster

joint_trajectory_controller:
  type: joint_trajectory_controller/JointTrajectoryController
  name: joint_trajectory_controller
  joints:
    - hip_joint
    - knee_joint
    - ankle_joint
  interface_name: position
  command_interfaces:
    - position
  state_interfaces:
    - position
    - velocity

